public class Day24C3 {
    
    string name='shashank siddamsetty';
    string name1='K uday';
     decimal salary=45000;
        
     public void name(){
       system.debug('Name:'+name);
         
   }
    public void hike(){
        system.debug('Name:'+name);
        system.debug('salary:'+salary);
       
        decimal hike=0.10*salary;
        decimal newsalary=salary+hike;
        system.debug('newsalary:'+newsalary);
        
        
    }
    public void value(integer noofunitssold,decimal price){
        system.debug('Name:'+name1);
        system.debug('no of units sold:'+noofunitssold);
        system.debug('price:'+price);
        decimal totalValue=noofunitssold*price;
        system.debug('Total value:'+totalvalue);
        
    }
    
    
    
}