public class Day30H2 extends Day30H1 {
    public void calculatearea(integer l,integer w)
    {
        rectangle( l,w);

    }
    public void calculatearea(decimal a)
    {
        square(a);
    }
    public void calculatearea(decimal pi,decimal r)
    {
        circle(pi,r);
    }
   
 /*Day30H2 obj =new Day30H2();
obj.calculatearea(10);*/

}

/*Day30H2 obj =new Day30H2();
obj.calculatearea(10);*/