public class Day31C3 {
    public integer x=100;
    public integer y;
    public integer z;
    public string s;
    public decimal d;
    public list<list<integer>> a = new list<list<integer>>();
 public list<list<list<integer>>> b =new list<list<list<integer>>>();
   
    
    /*public Day31C3()
    {
        this.s = 'commercecx';
        this.d = 8954.478;
    }*/
    public Day31C3()
    {
        this.y = y;
        this.s='commercecx';
        this.d=7453.2541;
    }
    public Day31C3(decimal d,string s,integer y)
    {
        this.y=y;
        this.s=s;
        this.d=d;
    }
    public void Day31C3(integer y,string s,decimal d)
    {
        this.y = y;
        this.s = s;
        this.d = 1452.35;
    }
    public void addnum()
    {
        system.debug('x='+x);
        system.debug('y='+y);
        system.debug('z='+z);
        system.debug('s='+s);
        system.debug('d='+d);
        z=x+y;
        system.debug('x='+x);
        system.debug('y='+y);
        system.debug('z='+z);
       
    }

}
/*Day31C3 obj4 =new Day31C3(213);
obj4.addnum();
system.debug('x='+obj4.x);
system.debug('y='+obj4.y);
system.debug('z='+obj4.z);
system.debug('s='+obj4.s);
system.debug('D='+obj4.d);*/