public class Day36H5 {
    //Write an Apex class using Merge two Employment website records using database class method
    public void mergingEmpWebRecords()
    {
        /*Employement_Website_Name__c e1=[select Name,Website__c
                                         from Employement_Website_Name__c where Name='Naukri'];
        
        Employement_Website_Name__c e2=[select Name,Website__c
                                         from Employement_Website_Name__c where Name='apna'];*/
        
        
        
      //salesforce supports only Leads, Contacts and Accounts
    }

}